// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnRyqykR6J5jkUEWfN83H2HB-dUSOQdR0',
    appId: '1:1017455608395:web:dec83e86441f700bc003ce',
    messagingSenderId: '1017455608395',
    projectId: 'noteapp-ee851',
    authDomain: 'noteapp-ee851.firebaseapp.com',
    storageBucket: 'noteapp-ee851.appspot.com',
    measurementId: 'G-DQ4NH2HGJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmliwm2mnpZ2QOpiZuxUdYDLMJLge2I_g',
    appId: '1:1017455608395:android:56e6211b88b2f325c003ce',
    messagingSenderId: '1017455608395',
    projectId: 'noteapp-ee851',
    storageBucket: 'noteapp-ee851.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYUsqml5z3eQzhY6uB6kg3HMLetKsvzbE',
    appId: '1:1017455608395:ios:2fe62e9cda13191fc003ce',
    messagingSenderId: '1017455608395',
    projectId: 'noteapp-ee851',
    storageBucket: 'noteapp-ee851.appspot.com',
    iosBundleId: 'com.example.noteWithFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYUsqml5z3eQzhY6uB6kg3HMLetKsvzbE',
    appId: '1:1017455608395:ios:158d6186a304bbefc003ce',
    messagingSenderId: '1017455608395',
    projectId: 'noteapp-ee851',
    storageBucket: 'noteapp-ee851.appspot.com',
    iosBundleId: 'com.example.noteWithFb.RunnerTests',
  );
}
